version: '3'

services:
  telegraf:
    image: telegraf:mgarciate
    build:
      context: ./telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - monitoring_network
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - monitoring_network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myadmin
      - DOCKER_INFLUXDB_INIT_PASSWORD=myadminpassword
      - DOCKER_INFLUXDB_INIT_ORG=speedtest
      - DOCKER_INFLUXDB_INIT_BUCKET=speedtest
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=J4l_F2IPPpSgBS2EBPErHTZO_ZZEu-ul-aHdnMAFS5SGF3WdlpTy0YDLkH8W8b2I7rX8syWFbQaW1oiTpUZjgQ==

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

networks:
  monitoring_network:
    driver: bridge

volumes:
  influxdb_data: