{
 "title": "TICK - Speedtest",
 "description": "Display the data collected using Telegraf and Speedtest CLI, stored in InfluxDB\nhttps://github.com/psilvaazevedo/TICK-Speedtest-Grafana",
 "tags": [
  "Speedtest",
  "InfluxDb",
  "Telegraf",
  "ISP",
  "TICK"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "st_hosts",
    "label": "SpeedTest_Hosts",
    "query": "SHOW TAG VALUES ON \"speedtest\" FROM \"Speedtest\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"download_bandwidth\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v:r._value) * float(v: 8) / float(v: 1000000) }))\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"download_bandwidth\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v:r._value) * float(v: 8) / float(v: 1000000) }))\n",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"upload_bandwidth\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v:r._value)* float(v: 8) / float(v: 1000000)}))\n",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"upload_bandwidth\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v:r._value)* float(v: 8) / float(v: 1000000) }))\n",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 131072" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"ping_latency\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "ping_latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Ping Latency / Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"Speedtest\" and \n      r._field == \"ping_latency\"\n  )\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"Speedtest\" and \n      r._field == \"ping_jitter\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"Speedtest\" and \n      r._field == \"download_latency_iqm\"\n  )\n"
    },
    {
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"Speedtest\" and \n      r._field == \"upload_latency_iqm\"\n  )\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"Speedtest\" and\n    r._field == \"ping_jitter\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "ping_jitter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Tests Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "limit": 10,
     "measurement": "Speedtest",
     "query": "from(bucket: \"speedtest\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n      r._measurement == \"Speedtest\" and\n      (r._field == \"host\" or \n       r._field == \"server_id\" or \n       r._field == \"server_host\" or\n       r._field == \"server_ip\" or\n       r._field == \"server_location\" or\n       r._field == \"result_url\" or\n       r._field == \"packetLoss\")\n  )\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 5)\n",
     "select": [
      [
       { "params": [ "server_id" ], "type": "field" }
      ],
      [
       { "params": [ "server_host" ], "type": "field" }
      ],
      [
       { "params": [ "server_ip" ], "type": "field" }
      ],
      [
       { "params": [ "server_location" ], "type": "field" }
      ],
      [
       { "params": [ "result_url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "InfluxDB" }
     ]
    }
   ]
  }
 ]
}